### PR TITLE
Lin_Res_E functionality 

### PR DESCRIPTION
**Pull request by schmittsche**
As coded in Liege with little improvements (help message, cleaned up function in phononmode.cpp)

### CODE REVIEW

**Comment by piti-diablotin** [comment]
Here you are !
I'll probably improve a little bit things according to your requests in the next weeks.

**Comment by schmittsche** [comment]
Nice :)


---------------------------------------------------------------
Michael Marcus Schmitt

*Doctorant/Boursier FRIA *

*Theoretical Materials Physics Research Group *

*Université de Liege *
*Phone: +32483416771*





*Allée du 6 août, 19 B5a Building - Office 3/12B- 4000 Sart
TilmanBELGIUMhttp://www.phythema.ulg.ac.be/
<http://www.phythema.ulg.ac.be/>*
---------------------------------------------------------------




2017-11-21 8:35 GMT+01:00 piti-diablotin <notifications@github.com>:

**Comment by schmittsche** [comment]
Maybe a little thing.  Could we include my name in the header of maybe
phononmode.cpp or somewhere? Just, if ever somebody ask for my contribution
there (e.g. the comittée which will have to verify the renewal of my
grant).

Best,
Marcus



---------------------------------------------------------------
Michael Marcus Schmitt

*Doctorant/Boursier FRIA *

*Theoretical Materials Physics Research Group *

*Université de Liege *
*Phone: +32483416771*





*Allée du 6 août, 19 B5a Building - Office 3/12B- 4000 Sart
TilmanBELGIUMhttp://www.phythema.ulg.ac.be/
<http://www.phythema.ulg.ac.be/>*
---------------------------------------------------------------




2017-11-22 11:17 GMT+01:00 Marcus Schmitt <mrcsschmitt@googlemail.com>:

**Comment by piti-diablotin** [comment]
Yes sure of course !
Feel free to add you name where you worked !
Make a new pull request and I'll merge

**Pull request merged**
